Admin-Portal-VDS/Admin-Portal

frontend/src/components/dashboard/body/Body.vue
frontend/src/components/dashboard/header/Header.vue
frontend/src/components/dashboard/left-navigation/LeftNavigation.vue
frontend/src/components/login/Login.vue

I have created a simple directory structure that targets the following components
1. body
2. left naviagation
3. header

Added simple component structure.

---

src/components/dashboard/header/DashboardHeader.vue

TASK-1.1-Reducing the size of Help and Visit store button

---

.husky/pre-commit
README.md
babel.config.js
jsconfig.json
package-lock.json
package.json
public/index.html
src/App.vue
src/components/dashboard/AdminDashboard.vue
src/components/dashboard/body/AdminBody.vue
src/components/dashboard/header/DashboardHeader.vue
src/components/dashboard/left-navigation/LeftNavigation.vue
src/components/dashboard/left-navigation/NavigationDropdown.vue
src/components/dashboard/left-navigation/ProfileSection.vue
src/components/login/LoginPage.vue
src/main.js
src/router/index.js
vue.config.js

1. Added husky to manage and run pre commit hooks
2. Added lint-staged to lint only staged files
3. Applied consistent formatting to existing codebase 
To format the entire project manually, run:
```npm run prettier```
or
When you stage files with:
```git add  <file>```  
and then commit using
```git commit -m <message> ```
husky triggers the pre-commit hook that formats the staged files using prettier and re-stage them.
@dnagegowda2 @cbug09 

TASK-4.1-Seting Up Linting In Pre Commit Hook

---

src/components/dashboard/header/DashboardHeader.vue

@vanshika-dargan-18 , @cbug09 
cc:@pratikjoshivonage

Task-1.2-Moving to the right and reducing the size of Vonage-icon.

---

src/components/common/DropdownComponent.vue
src/components/common/HeadingComponent.vue
src/components/common/NavigationBar.vue
src/components/common/PrimaryButton.vue
src/components/common/SecondaryButton.vue
src/components/common/TableComponent.vue
src/components/dashboard/body/AdminBody.vue

Creating Button Components.
@vanshika-dargan-18 @Shubham-rajput09 @malaypandey98  
cc:@malaypandey98 @pratikjoshivonage

Task -6.1-code-update: Creating reusable button components.

---

src/components/login/ContactUs.vue
src/components/login/ForgotPassword.vue
src/components/login/LoginPage.vue

@malaypandey98 @pratikjoshivonage
cc : @vanshika-dargan-18 @Dys-Mn11

code-update:created contactus and forgotpassword pages

---

src/components/common/NavigationBar.vue
src/components/dashboard/body/AdminBody.vue

@Shubham-rajput09 @vanshika-dargan-18 
cc: @malaypandey98 @pratikjoshivonage

code-update:added navigationbar component

---

public/index.html
src/components/login/LoginPage.vue

@pratikjoshivonage 
cc : @Dys-Mn11 @vanshika-dargan-18

Added Show/Hide Password Toggle and disable/enable for login.

---

src/components/common/NavigationBar.vue
src/components/dashboard/body/AdminBody.vue
src/json/tableData.json

@pratikjoshivonage
cc: @vanshika-dargan-18 @Shubham-rajput09

code-update:added audit log table

---

src/components/common/UserForm.vue
src/components/common/adbulk.vue

@pratikjoshivonage 
cc : @Dys-Mn11 @vanshika-dargan-18

Added User form and bulk page

---

.husky/pre-commit
babel.config.js
jest.config.js
package-lock.json
package.json
src/components/common/AddBulk.vue
tests/unit/HeadingComponent.spec.js

@Shubham-rajput09 @vanshika-dargan-18 

code-update:writing unit test on frontend using jest

---

src/components/common/UserForm.vue
tests/unit/CheckBoxDropDown.spec.js
tests/unit/HeadingComponent.spec.js
tests/unit/TableComponent.spec.js
tests/unit/UserForm.spec.js
tests/unit/__snapshots__/HeadingComponent.spec.js.snap

@vanshika-dargan-18 @Shubham-rajput09

bug-fix:fixed-inconsistency-in-userform

---

src/components/common/AddBulk.vue
src/components/common/SearchFilterBar.vue
src/components/common/UserForm.vue
src/router/index.js
tests/unit/common/__snapshots__/AddBulk.spec.js.snap
tests/unit/common/__snapshots__/UserForm.spec.js.snap

I have integrated Add Form and Add New Form 
using routes.
@Vanshika-Dargan @Shubham-rajput09

code-update:integrating-bulk-add-form

---

package-lock.json
package.json
src/components/login/ContactUs.vue
src/components/login/LoginPage.vue
tests/unit/ContactUs.spec.js
tests/unit/__snapshots__/ContactUs.spec.js.snap
tests/unit/__snapshots__/LoginPage.spec.js.snap

@vanshika-dargan-18 @Dys-Mn11 

Added sign up form in login page

---

src/components/common/SectionTabs.vue
src/components/dashboard/AdminDashboard.vue
src/components/dashboard/body/AdminBody.vue
src/json/sectionTab.json
src/json/tableData.json
src/pages/Extensions.vue
src/pages/GroupManagement.vue
src/pages/UserPermissions.vue
src/pages/Users.vue
src/stores/selectedOption.js
tests/unit/common/SectionTabs.spec.js
tests/unit/common/__snapshots__/SectionTabs.spec.js.snap

Task Overview:
Added dynamic page changes with navigation. 
cc: @Dys-Mn11 @Shubham-rajput09 @pratikjoshivonage

code-update: added dynaimc page change on navigation

---

src/components/common/AddNewGroup.vue
tests/unit/__snapshots__/ContactUs.spec.js.snap

Code Updated : Added GroupForm

---

src/components/login/LoginPage.vue

code-update:adding-regex-in-login-page

---

src/components/common/PermissionTable.vue
src/components/login/LoginPage.vue
src/pages/UserPermissions.vue

Task Overview:
Added Permission Table Component.
cc: @Dys-Mn11 @Shubham-rajput09 @pratikjoshivonage

code-update:general fixes and setting up permission table component

---

src/components/dashboard/left-navigation/NavigationDropdown.vue

Tak Overview:
Making Pages Dropdown to be open when we navigates from login page to dashboard.
cc: @pratikjoshivonage @Shubham-rajput09 @Vanshika-Dargan

code-update:fixing-pages-dropdown-issue

---

src/components/common/AddBulk.vue
tests/unit/common/__snapshots__/AddBulk.spec.js.snap

Task Overview:
Adding cancel button to go back to previous page.
cc:  @pratikjoshivonage @Vanshika-Dargan  @Shubham-rajput09

code-update:adding-cancel-button-in-forms

---

src/components/common/PermissionTable.vue

Code Updated : Added permission table for user permission

---

src/components/common/CancelButton.vue
src/components/common/UserForm.vue
tests/unit/common/__snapshots__/UserForm.spec.js.snap

code-update:adding-cancel-button-in-add-user-form

---

src/components/common/AddNewGroup.vue

I have added close button and esc keyboard event listener for group form.

code-update:adding-cancel-button-in-group-form

---

src/components/common/AddBulk.vue
tests/unit/common/AddBulk.spec.js
tests/unit/common/__snapshots__/AddBulk.spec.js.snap

I have added input validations for add bulk form.
@pratikjoshivonage

code-update:input-validations-added-to-add-bulk-form

---

src/components/login/ContactUs.vue
tests/unit/ContactUs.spec.js
tests/unit/__snapshots__/ContactUs.spec.js.snap

I have added input validations in contact us form, also added cancel and esc event listener to back to previus page.

code-update:adding-input-validations-for-contactus-form

---

Dockerfile
package-lock.json
package.json
src/components/login/LoginPage.vue
src/services/axios.js

Task Overview:
Integrated signup api 
cc: @pratikjoshivonage @Dys-Mn11 @Shubham-rajput09

code-update:integrated signup api

---

src/components/login/LoginPage.vue
src/composables/useAuth.js
src/router/index.js

Task Overview:
Integrated login api 
cc: @pratikjoshivonage @Dys-Mn11 @Shubham-rajput09

code-update: integrated-login-api-and-token-stored-in-session-storage
